version: '{build}'
shallow_clone: true

platform: x64
configuration: Debug

environment:
  MSBUILD_FLAGS: /verbosity:minimal /maxcpucount
  matrix:
  - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2019
    CMAKE_GENERATOR: "Visual Studio 16 2019 Win64"

matrix:
  fast_finish: true

before_build:
  - cmake --version
  - cmake -H. -Bbuild -G "%CMAKE_GENERATOR%"

build_script:
  - cmake --build build --target ALL_BUILD -- %MSBUILD_FLAGS%

test_script:
  - cmake --build build --target RUN_TESTS -- %MSBUILD_FLAGS%

