name: amd64 FreeBSD

on: [push, pull_request]

jobs:
  # Only macos runner provide virtualisation with vagrant/virtualbox installed.
  freebsd:
    runs-on: macos-10.15
    steps:
    - uses: actions/checkout@v3
    - name: vagrant version
      run: Vagrant --version
    - name: VirtualBox version
      run: virtualbox -h
    - name: Build
      run: make --directory=ci freebsd_build
