# ref: https://toolchains.bootlin.com/
name: powerpc Toolchain CMake

on: [push, pull_request, workflow_dispatch]

concurrency:
  group: ${{github.workflow}}-${{github.ref}}
  cancel-in-progress: true

# Building using the github runner environement directly.
jobs:
  powerpc:
    strategy:
      matrix:
        targets: [
          # https://go.dev/doc/install/source#environment
          ppc64, # alias to ppc64-power8
          ppc64le, # alias ppc64le-power8
          ppc64-power8, # bootlin
          ppc64le-power8, # bootlin
        ]
      fail-fast: false
    name: Linuxâ€¢Toolchain ${{matrix.targets}}
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v5
    - name: Build env stage
      run: make --directory=ci toolchain_${{matrix.targets}}_env
    - name: Build devel stage
      run: make --directory=ci toolchain_${{matrix.targets}}_devel
    - name: Build toolchain stage
      run: make --directory=ci toolchain_${{matrix.targets}}_toolchain
    - name: Build build stage
      run: make --directory=ci toolchain_${{matrix.targets}}_build
    - name: Build Test stage
      run: make --directory=ci toolchain_${{matrix.targets}}_test
