name: riscv64 Toolchain

on: [push, pull_request, workflow_dispatch]

# Building using the github runner environement directly.
jobs:
  riscv64:
    strategy:
      matrix:
        targets: [
          # https://go.dev/doc/install/source#environment
          riscv64, # bootlin
        ]
      fail-fast: false
    name: Linux â€¢ Toolchain ${{ matrix.targets }}
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Build env stage
      run: make --directory=ci ${{ matrix.targets }}_env
    - name: Build devel stage
      run: make --directory=ci ${{ matrix.targets }}_devel
    - name: Build toolchain stage
      run: make --directory=ci ${{ matrix.targets }}_toolchain
    - name: Build build stage
      run: make --directory=ci ${{ matrix.targets }}_build
    - name: Build Test stage
      run: make --directory=ci ${{ matrix.targets }}_test
